"""CLI entry point for fast-readme-ai.

Provides the ``fast-readme`` command using Typer with Rich output for
colored terminal feedback, spinners, and formatted error messages.
"""

import sys
import time
from importlib.metadata import version as pkg_version
from typing import Optional

import typer
from rich.console import Console

from core.engine import generate

app = typer.Typer(
    name="fast-readme",
    help="⚡ AI-powered README generator for developers.",
    add_completion=False,
    no_args_is_help=False,
)

console = Console()


def _version_callback(value: bool) -> None:
    """Print version and exit when --version is passed.

    Args:
        value: Whether the flag was set.
    """
    if value:
        try:
            v = pkg_version("fast-readme-ai")
        except Exception:
            v = "1.0.0"
        console.print(f"fast-readme-ai v{v}")
        raise typer.Exit()


@app.command()
def main(
    source: str = typer.Argument(
        ".",
        help="Local project path or GitHub URL to analyze.",
    ),
    output: str = typer.Option(
        "FASTREADME.md",
        "--output",
        "-o",
        help="Output filename. Defaults to FASTREADME.md to avoid overwriting existing docs.",
    ),
    name: Optional[str] = typer.Option(
        None,
        "--name",
        "-n",
        help="Project name override. Inferred from directory name if omitted.",
    ),
    model: str = typer.Option(
        "gemini-2.5-flash",
        "--model",
        "-m",
        help="Gemini model to use for generation.",
    ),
    no_save: bool = typer.Option(
        False,
        "--no-save",
        help="Print README to stdout only, do not write to file.",
    ),
    debug: bool = typer.Option(
        False,
        "--debug",
        help="Show full Python tracebacks on error.",
    ),
    version: Optional[bool] = typer.Option(
        None,
        "--version",
        callback=_version_callback,
        is_eager=True,
        help="Print version and exit.",
    ),
) -> None:
    """Generate a professional README.md for any project.

    Accepts a local folder path or a GitHub repository URL.  Analyzes the
    project structure, detects the tech stack, reads key source files, and
    uses the Google Gemini API to produce a complete README.

    Examples::

        fast-readme .
        fast-readme /path/to/project
        fast-readme https://github.com/user/repo
        fast-readme . --output MY_README.md
        fast-readme . --no-save
    """
    start_time = time.time()

    console.print("\n[bold cyan]⚡ fast-readme-ai[/bold cyan]")
    console.print("Analyzing project...\n")

    try:
        # Determine output path
        out_path = None if no_save else output

        # Run the engine with a spinner
        with console.status("[bold green]Generating README with Gemini...", spinner="dots"):
            result = generate(
                source=source,
                project_name=name,
                output_path=out_path,
                model=model,
            )

        if not result.success:
            console.print(f"\n[bold red]✘ Error:[/bold red] {result.error}")
            if result.error and "Gemini API" in result.error:
                console.print(
                    "[dim]→ Check your GEMINI_API_KEY in .env[/dim]"
                )
            raise typer.Exit(code=1)

        # Print success steps
        console.print("[green]✔[/green] Directory scanned")

        stack_items = []
        for items_list in result.stack.values():
            stack_items.extend(items_list)
        if stack_items:
            console.print(
                f"[green]✔[/green] Stack detected: {', '.join(stack_items[:6])}"
            )
        else:
            console.print("[green]✔[/green] Stack analyzed")

        console.print("[green]✔[/green] Prompt built")
        console.print("[green]✔[/green] README generated by Gemini")

        if no_save:
            console.print("\n---\n")
            console.print(result.readme_content)
        else:
            console.print(
                f"\n[bold cyan]📄 Saved to:[/bold cyan] {output}"
            )

        elapsed = time.time() - start_time
        console.print(f"\n[dim]Done in {elapsed:.1f}s[/dim]\n")

    except typer.Exit:
        raise
    except Exception as exc:
        if debug:
            raise
        console.print(f"\n[bold red]✘ Unexpected error:[/bold red] {exc}")
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
